apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stock-tracker
  labels:
    app: stock-tracker
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stock-tracker
  labels:
    app: stock-tracker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stock-tracker
subjects:
  - kind: ServiceAccount
    name: stock-tracker
