---
apiVersion: v1
kind: Service
metadata:
  name: stock-tracker
  labels:
    app: stock-tracker

spec:
  type: LoadBalancer
  ports:
    -port :443
     targetPort: 7443
     protocol: TCP
  selector:
    app: stock-tracker
    state: serving
  
